# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/wedow/homework
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build -ldflags "-X main.domain=$DROPLET_HOST"
      - deploy:
          name: Deploy Homework
          command: |
            echo "$DROPLET_HOST,$DROPLET_IP ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNU4p+Dp5mMajzS2Ks24qor26Lu3ssIMgBEs4o3ueI91OJCIT25vQG3Z7u256vD2938xNXsu4oDeF4pSnpSkaEM=" >> ~/.ssh/known_hosts
            ssh -v $DROPLET_USER@$DROPLET_HOST "rm homework"
            scp -v /go/src/github.com/wedow/homework/homework $DROPLET_USER@$DROPLET_HOST:~
            ssh -v $DROPLET_USER@$DROPLET_HOST "killall homework; nohup ./homework >> homework.log 2>&1 &"